name: expense_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.4.54
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  simple_animations: ^3.1.0
  page_transition: ^2.1.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0

 
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  


  flutter_lints: ^4.0.0

flutter:

 
  uses-material-design: true


  assets:
       - images/
       

